api = "0.10"

[buildpack]
id = "libvips"
version = "1.0.0"
name = "libvips with libheif"
homepage = "https://github.com/mariochavez/heroku-buildpack-libvips"

[metadata]
include-files = ["bin/detect", "bin/compile", "bin/release", "README.md"]

[[metadata.dependencies]]
name = "libvips"
version = "8.17.0"

[[metadata.dependencies]]
name = "libheif"
version = "1.19.8"

[[stacks]]
id = "heroku-24"
